#leave only days in study

test14 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "14" & pRMT_allIDs$day > 282)
test14 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "14" & pRMT_allIDs$day > 282)
test15 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "15" & pRMT_allIDs$day > 222)
test16 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "16" & pRMT_allIDs$day > 223)
test17 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "17" & pRMT_allIDs$day > 214)
test18 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "18" & pRMT_allIDs$day > 214)
test19 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "19" & pRMT_allIDs$day > 194)
test20 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "20" & pRMT_allIDs$day > 188)
test21 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "21" & pRMT_allIDs$day > 264)
test22 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "22" & pRMT_allIDs$day > 293)
test23 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "23" & pRMT_allIDs$day > 267)
test24 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "24" & pRMT_allIDs$day > 186)
test25 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "25" & pRMT_allIDs$day > 280)
test26 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "26" & pRMT_allIDs$day > 140)
test27 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "27" & pRMT_allIDs$day > 222)
test28 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "28" & pRMT_allIDs$day > 291)
test29 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "29" & pRMT_allIDs$day > 232)
test30 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "30" & pRMT_allIDs$day > 199)
test31 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "31" & pRMT_allIDs$day > 261)
test32 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "32" & pRMT_allIDs$day > 249)
test33 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "33" & pRMT_allIDs$day > 92)
test34 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "34" & pRMT_allIDs$day > 245)
test35 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "35" & pRMT_allIDs$day > 252)
test36 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "36" & pRMT_allIDs$day > 269)
test37 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "37" & pRMT_allIDs$day > 226)
test38 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "38" & pRMT_allIDs$day > 245)
test39 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "39" & pRMT_allIDs$day > 192)
test40 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "40" & pRMT_allIDs$day > 219)
test41 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "41" & pRMT_allIDs$day > 201)
test42 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "42" & pRMT_allIDs$day > 182)
test43 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "43" & pRMT_allIDs$day > 187)
test44 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "44" & pRMT_allIDs$day > 223)
test45 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "45" & pRMT_allIDs$day > 212)
test46 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "46" & pRMT_allIDs$day > 216)
test47 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "47" & pRMT_allIDs$day > 213)
test48 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "48" & pRMT_allIDs$day > 190)
test49 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "49" & pRMT_allIDs$day > 290)
test50 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "50" & pRMT_allIDs$day > 189)
test51 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "51" & pRMT_allIDs$day > 250)
test52 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "52" & pRMT_allIDs$day > 243)
test53 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "53" & pRMT_allIDs$day > 154)
test54 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "54" & pRMT_allIDs$day > 191)
test55 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "55" & pRMT_allIDs$day > 135)
test56 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "56" & pRMT_allIDs$day > 156)
test57 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "57" & pRMT_allIDs$day > 197)
test58 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "58" & pRMT_allIDs$day > 354)
test59 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "59" & pRMT_allIDs$day > 182)
test60 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "60" & pRMT_allIDs$day > 214)
test61 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "61" & pRMT_allIDs$day > 154)
test62 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "62" & pRMT_allIDs$day > 105)
test63 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "63" & pRMT_allIDs$day > 183)
test64 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "64" & pRMT_allIDs$day > 156)
test65 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "65" & pRMT_allIDs$day > 239)
test66 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "66" & pRMT_allIDs$day > 144)
test67 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "67" & pRMT_allIDs$day > 238)
test68 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "68" & pRMT_allIDs$day > 160)
test69 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "69" & pRMT_allIDs$day > 147)
test70 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "70" & pRMT_allIDs$day > 253)
test71 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "71" & pRMT_allIDs$day > 176)
test72 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "72" & pRMT_allIDs$day > 181)
test73 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "73" & pRMT_allIDs$day > 257)
test74 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "74" & pRMT_allIDs$day > 251)
test75 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "75" & pRMT_allIDs$day > 182)
test76 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "76" & pRMT_allIDs$day > 239)
test77 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "77" & pRMT_allIDs$day > 122)
test78 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "78" & pRMT_allIDs$day > 164)
test79 <- subset(pRMT_allIDs, pRMT_allIDs$record_ID == "79" & pRMT_allIDs$day > 144)

test2 <- anti_join(pRMT_allIDs, test14)
test2 <- anti_join(test2, test15)
test2 <- anti_join(test2, test16)
test2 <- anti_join(test2, test17)
test2 <- anti_join(test2, test18)
test2 <- anti_join(test2, test19)
test2 <- anti_join(test2, test20)
test2 <- anti_join(test2, test21)
test2 <- anti_join(test2, test22)
test2 <- anti_join(test2, test23)
test2 <- anti_join(test2, test24)
test2 <- anti_join(test2, test25)
test2 <- anti_join(test2, test26)
test2 <- anti_join(test2, test27)
test2 <- anti_join(test2, test28)
test2 <- anti_join(test2, test29)
test2 <- anti_join(test2, test30)
test2 <- anti_join(test2, test31)
test2 <- anti_join(test2, test32)
test2 <- anti_join(test2, test33)
test2 <- anti_join(test2, test34)
test2 <- anti_join(test2, test35)
test2 <- anti_join(test2, test36)
test2 <- anti_join(test2, test37)
test2 <- anti_join(test2, test38)
test2 <- anti_join(test2, test39)
test2 <- anti_join(test2, test40)
test2 <- anti_join(test2, test41)
test2 <- anti_join(test2, test42)
test2 <- anti_join(test2, test43)
test2 <- anti_join(test2, test44)
test2 <- anti_join(test2, test45)
test2 <- anti_join(test2, test46)
test2 <- anti_join(test2, test47)
test2 <- anti_join(test2, test48)
test2 <- anti_join(test2, test49)
test2 <- anti_join(test2, test50)
test2 <- anti_join(test2, test51)
test2 <- anti_join(test2, test52)
test2 <- anti_join(test2, test53)
test2 <- anti_join(test2, test54)
test2 <- anti_join(test2, test55)
test2 <- anti_join(test2, test56)
test2 <- anti_join(test2, test57)
test2 <- anti_join(test2, test58)
test2 <- anti_join(test2, test59)
test2 <- anti_join(test2, test60)
test2 <- anti_join(test2, test61)
test2 <- anti_join(test2, test62)
test2 <- anti_join(test2, test63)
test2 <- anti_join(test2, test64)
test2 <- anti_join(test2, test65)
test2 <- anti_join(test2, test66)
test2 <- anti_join(test2, test67)
test2 <- anti_join(test2, test68)
test2 <- anti_join(test2, test69)
test2 <- anti_join(test2, test70)
test2 <- anti_join(test2, test71)
test2 <- anti_join(test2, test72)
test2 <- anti_join(test2, test73)
test2 <- anti_join(test2, test74)
test2 <- anti_join(test2, test75)
test2 <- anti_join(test2, test76)
test2 <- anti_join(test2, test77)
test2 <- anti_join(test2, test78)
test2 <- anti_join(test2, test79)
